library(ggbiplot)
library(arules)
library('Hmisc')
library("ggpubr")
library(sva)
library(limma)
library(plyr)
library("caret")
library('doParallel')
library('data.table')
cl <- makeCluster(4)
registerDoParallel(cl)
require("VennDiagram")
library(devtools)
require(ggplot2)

#install_github("GabrielHoffman/variancePartition")
library(variancePartition)
library('variancePartition')
library("rmcfs")
library("Boruta")
library("R.ROSETTA")
library(biomaRt)
library(dynamicTreeCut)
library(gridExtra)
library(cowplot)

